name: sortir_a_nantes
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  http: ^1.5.0  
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  multi_select_flutter: ^4.1.3
  geolocator: ^14.0.2
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.4.2
  shared_preferences: ^2.5.3
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
